use crate::settings::Key;

use eframe::egui;
use rdev::Key as RdevKey;

pub fn map_rdev_to_key(key: RdevKey) -> Option<Key> {
    use RdevKey as R;
    Some(match key {
        R::F6 => Key::F6,
        R::F7 => Key::F7,
        R::F8 => Key::F8,
        R::F9 => Key::F9,
        R::F10 => Key::F10,
        R::F11 => Key::F11,
        R::F12 => Key::F12,
        R::Space => Key::Space,
        R::Return => Key::Enter,
        R::Escape => Key::Escape,
        R::KeyA => Key::Char('A'),
        R::KeyB => Key::Char('B'),
        R::KeyC => Key::Char('C'),
        R::KeyD => Key::Char('D'),
        R::KeyE => Key::Char('E'),
        R::KeyF => Key::Char('F'),
        R::KeyG => Key::Char('G'),
        R::KeyH => Key::Char('H'),
        R::KeyI => Key::Char('I'),
        R::KeyJ => Key::Char('J'),
        R::KeyK => Key::Char('K'),
        R::KeyL => Key::Char('L'),
        R::KeyM => Key::Char('M'),
        R::KeyN => Key::Char('N'),
        R::KeyO => Key::Char('O'),
        R::KeyP => Key::Char('P'),
        R::KeyQ => Key::Char('Q'),
        R::KeyR => Key::Char('R'),
        R::KeyS => Key::Char('S'),
        R::KeyT => Key::Char('T'),
        R::KeyU => Key::Char('U'),
        R::KeyV => Key::Char('V'),
        R::KeyW => Key::Char('W'),
        R::KeyX => Key::Char('X'),
        R::KeyY => Key::Char('Y'),
        R::KeyZ => Key::Char('Z'),
        R::Num0 => Key::Char('0'),
        R::Num1 => Key::Char('1'),
        R::Num2 => Key::Char('2'),
        R::Num3 => Key::Char('3'),
        R::Num4 => Key::Char('4'),
        R::Num5 => Key::Char('5'),
        R::Num6 => Key::Char('6'),
        R::Num7 => Key::Char('7'),
        R::Num8 => Key::Char('8'),
        R::Num9 => Key::Char('9'),
        _ => return None,
    })
}

pub fn map_egui_key_to_key(k: egui::Key) -> Option<Key> {
    use egui::Key as E;
    Some(match k {
        E::F6 => Key::F6,
        E::F7 => Key::F7,
        E::F8 => Key::F8,
        E::F9 => Key::F9,
        E::F10 => Key::F10,
        E::F11 => Key::F11,
        E::F12 => Key::F12,
        E::Space => Key::Space,
        E::Enter => Key::Enter,
        E::Escape => Key::Escape,
        E::A => Key::Char('A'),
        E::B => Key::Char('B'),
        E::C => Key::Char('C'),
        E::D => Key::Char('D'),
        E::E => Key::Char('E'),
        E::F => Key::Char('F'),
        E::G => Key::Char('G'),
        E::H => Key::Char('H'),
        E::I => Key::Char('I'),
        E::J => Key::Char('J'),
        E::K => Key::Char('K'),
        E::L => Key::Char('L'),
        E::M => Key::Char('M'),
        E::N => Key::Char('N'),
        E::O => Key::Char('O'),
        E::P => Key::Char('P'),
        E::Q => Key::Char('Q'),
        E::R => Key::Char('R'),
        E::S => Key::Char('S'),
        E::T => Key::Char('T'),
        E::U => Key::Char('U'),
        E::V => Key::Char('V'),
        E::W => Key::Char('W'),
        E::X => Key::Char('X'),
        E::Y => Key::Char('Y'),
        E::Z => Key::Char('Z'),
        _ => return None,
    })
}
